name: LunarWand
version: 1.0.0
main: hu.galaxy.lunarwand.LunarWandPlugin
api-version: '1.21'
author: Galaxy
commands:
  lunarwand:
    description: Give the Lunar Wand.
    usage: /lunarwand give
    permission: lunarwand.admin
permissions:
  lunarwand.admin:
    default: op
